# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

st.set_page_config(page_title="Dashboard Analisis Siswa", layout="wide")

st.set_page_config(page_title="Dashboard Analisis Siswa", layout="wide")
st.title("📊 Dashboard Analisis Hasil Simulasi Siswa")
st.markdown("Analisis otomatis untuk data siswa")

file = st.file_uploader("/content/data_simulasi_50_siswa_20_soal.xlsx", type="xlsx")

if file is None:
    st.info("Silakan upload file Excel terlebih dahulu")
    st.stop()

file_path = "/content/data_simulasi_50_siswa_20_soal.xlsx"
df = pd.read_excel(file_path)

indikator = df.apply(pd.to_numeric, errors="coerce")

mean_scores = indikator.mean()
total_avg = mean_scores.mean()
ikm = (total_avg / 4) * 100

def kategori(x):
    if x >= 80: return "Sangat Baik"
    elif x >= 65: return "Baik"
    elif x >= 50: return "Cukup"
    else: return "Kurang"

c1,c2,c3 = st.columns(3)
c1.metric("📈 Rata-rata Skor", f"{total_avg:.2f}")
c2.metric("🏷️ Kategori", kategori(ikm))
c3.metric("👥 Jumlah Siswa", len(df))

st.divider()

st.header("🎯 Analisis Kesulitan Soal")

gap = 4 - mean_scores
soal_sulit = gap.idxmax()

fig,ax = plt.subplots(figsize=(12,4))
gap.plot(kind="bar", ax=ax)
ax.set_title("Tingkat Kesulitan Tiap Soal")
ax.set_ylabel("Nilai GAP")
plt.xticks(rotation=45)

st.pyplot(fig)
st.warning(f"Soal paling sulit: **{soal_sulit}**")

st.divider()

st.header("🔗 Korelasi Antar Soal")

corr = indikator.corr()

fig,ax = plt.subplots(figsize=(8,6))
im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
plt.colorbar(im)

ax.set_xticks(range(len(corr.columns)))
ax.set_yticks(range(len(corr.columns)))
ax.set_xticklabels(corr.columns, rotation=90)
ax.set_yticklabels(corr.columns)

st.pyplot(fig)

st.divider()

st.header("📈 Analisis Regresi")
st.caption("Prediksi Soal terakhir dari soal lainnya")

X = sm.add_constant(indikator.iloc[:, :-1])
y = indikator.iloc[:, -1]

model = sm.OLS(y, X, missing="drop").fit()

coef = model.params[1:].sort_values(ascending=False).head(5)
r2 = model.rsquared

st.info(f"R² = {r2:.3f}")

st.subheader("5 Soal Paling Berpengaruh")
st.dataframe(coef.to_frame("Koefisien"))

st.divider()

st.header("👥 Segmentasi Siswa")

scaler = StandardScaler()
scaled = scaler.fit_transform(indikator.fillna(0))

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
cluster = kmeans.fit_predict(scaled)

indikator_cluster = indikator.copy()
indikator_cluster["Cluster"] = cluster

cluster_mean = indikator_cluster.groupby("Cluster").mean()
rank = cluster_mean.mean(axis=1).sort_values(ascending=False).index

map_seg = {
    rank[0]:"Mahir",
    rank[1]:"Menengah",
    rank[2]:"Dasar"
}
indikator_cluster["Kategori"] = indikator_cluster["Cluster"].map(map_seg)

st.dataframe(indikator_cluster.head())

st.success("Dashboard siap digunakan")